name: Lint YAML

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Verifier les fichiers YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable
              truthy: disable
